### ISSUE TITLE
Export metaMode() and un-export withMetaMode()

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shinymeta#64]
Seems like `metaMode()` could be useful for debugging purposes.

Also, I can't think of any reason why `withMetaMode()` is useful now (other than for facilitating explanation)

**Comment by jcheng5** [comment]
We discussed this in person--`metaMode()` is too tricky since it's impossible to understand its trinary nature without a very deep understanding of the implementation.

`withMetaMode` is useful mostly for facilitating explanation, yes; I don't think that is a problem, other than the fact that the name `withMetaMode` is so different from `expandChain`.
