### ISSUE TITLE
Indentation of the list of inputs breaks expandChain

### ISSUE THREAD

**Issue by etiennebacher** [rstudio/shinymeta#84]
I know that the title is not very clear, so here's an example:
```
library(shiny)
library(shinymeta)

small_mod_ui <- function(id){
  ns <- NS(id)
  selectInput(ns("test"), "test", choices = names(mtcars))
}
small_mod_server <- function(input, output, session){
  return(
    list(
      test_reactive = metaReactive({
        ..(input$test)
      }), 
      test_reactive_2 = metaReactive({
        ..(input$test)
      })
    )
  )
}

code_mod_ui <- function(id){
  ns <- NS(id)
  verbatimTextOutput(ns("show_code"))
}
code_mod_server <- function(input, output, session, com_between_mods){
  output$show_code <- renderPrint({
    expandChain(
      com_between_mods$test_reactive(),
      com_between_mods$test_reactive_2()
    )
  })
}

ui <- fluidPage(
  small_mod_ui("1"),
  code_mod_ui("1")
)

server <- function(input, output, session) {
  
  com_between_mods <- callModule(small_mod_server, "1")
  callModule(code_mod_server, "1", com_between_mods = com_between_mods)
  
}

shinyApp(ui, server)
```
This app throws an error:
> Warning: Error in : <text>:2:2: unexpected input
1: `1_test_reactive` <- "mpg"
2: 1_
    ^
  134: <Anonymous>

However, replacing
```
return(
  list(
      test_reactive = metaReactive({
        ..(input$test)
      }), 
      test_reactive_2 = metaReactive({
        ..(input$test)
      })
    )
  )
``` 
by
```
  return(list(test_reactive = metaReactive({ ..(input$test) }), test_reactive_2 = metaReactive({ ..(input$test) }) ))
```
(on a single line) seems to fix the problem.

Is it normal? If not, is it possible to fix this?

I also asked [on RStudio Community](https://community.rstudio.com/t/indentation-trouble-when-communicating-between-modules-with-shinymeta/64727) and [on StackOverflow](https://stackoverflow.com/questions/61676755/indentation-trouble-when-communicating-between-modules-with-shinymeta)

**Comment by jcheng5** [comment]
Wow, what a find :laughing:

The problem here stems from the use of `"1"` as the module ID. This causes shinymeta to attempt to assign variable names that begin with `1_`, which is illegal in R:

```
> 1_x <- TRUE
Error: unexpected input in "1_"
```

Putting everything on a single line works because it actually _breaks_ shinymeta's ability to infer what those metaReactives should be named. The logic to guess that makes some assumptions about the way the source code is formatted, it's pretty hacky (you can pass each `metaReactive` a `varname` argument to override this logic and just provide your own name). When shinymeta can't infer a name, it just picks a generic name (`var_1` and `var_2`) which obviously is legal.

If you change the module names from `"1"` to, say, `"one"` you should see the problem go away.

I'll add that you shouldn't use the same ID for two modules, even when they're related like this. `small_mod_ui` and `callModule(small_mod_server)` should use one ID, and `code_mod_ui` and `callModule(code_mod_server)` should use another ID.

**Comment by etiennebacher** [comment]
Perfect, thanks for the solution and the advice!
